export const filters = [
    "All",
    "Gaming",
    "Inventions",
    "Computer programming",
    "Kannada Cinema",
    "CPUs",
    "Music",
    "Thrillers",
    "Google",
    "Mixes",
    "Automobiles",
    "Cricket",
    "Live",
    "Dramedy",
    "Cars",
    "Blogs",
    "Technology",
    "Fitness",
    "Food",
    "Travel",
    "Education",
    "Science",
    "Health",
    "Sports",
    "Comedy",
    "Motivation",
    "DIY",
    "Photography",
    "Art",
    "Fashion",
    "Vlogs",
    "News",
    "Reviews",
    "Unboxing",
    "Animation",
    "Short Films",
    "Music Videos",
    "Podcasts",
    "Tech Reviews",
    "Documentaries",
    "Nature",
    "Pets",
    "Gaming Tutorials",
    "ASMR",
    "Self Improvement",
    "Lifestyle",
    "Meditation",
    "Business",
    "Finance",
    "Gaming News"
]
